### ISSUE TITLE
Default username/password?

### ISSUE THREAD

**Issue by Morgazmo** [flipboxstudio/mvvm-starter#6]
I apologise if it should have been apparent, but I can't find the username/password anywhere in the source code to get past the login screen. Do we need to implement authorisation, or is there dummy user info that we can use to see more of the app?

**Comment by aqidd** [comment]
hi @Morgazmo there is no default username / password - the login form was just implemented to showcase a login flow using REST API

just put random user id from jhttps://jsonplaceholder.typicode.com/users and any password
