### ISSUE TITLE
Dagger support

### ISSUE THREAD

**Issue by zishanj** [flipboxstudio/mvvm-starter#7]
When you are going to update your repository with Dagger as dependency injector?

**Comment by aqidd** [comment]
will probably do that around March of faster if @suhafer can handle it.

**Comment by stillie** [comment]
This is something i was wondering when i was looking into this project.

**Comment by aqidd** [comment]
Hi @zishanj @stillie , we're archiving this project and our starter is moving to https://github.com/medigoid/ModularStarter :)
