### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by kauramanp** [flipboxstudio/mvvm-starter#8]
Firstly it was showing error in data binding library that was sorted out by using 2.0.0 version. Next aapt2 error that was solved by using android.enableAapt2=false in gradle properties. I am unable to resolve Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process C:\Users\admin\AppData\Local\Android\Sdk\build-tools\26.0.2\aapt.exe with arguments {package -f --no-crunch -I C:\Users\admin\AppData\Local\Android\Sdk\platforms\android-27\android.jar -M \\?\E:\android example projects\mvvm-starter-master\mvvm-starter-master\app\build\intermediates\manifests\full\dev\debug\AndroidManifest.xml -S E:\android example projects\mvvm-starter-master\mvvm-starter-master\app\build\intermediates\res\merged\dev\debug -m -J \\?\E:\android example projects\mvvm-starter-master\mvvm-starter-master\app\build\generated\source\r\dev\debug -F E:\android example projects\mvvm-starter-master\mvvm-starter-master\app\build\intermediates\res\dev\debug\resources-devDebug.ap_ --custom-package id.co.flipbox.mvvmstarter -0 apk --output-text-symbols \\?\E:\android example projects\mvvm-starter-master\mvvm-starter-master\app\build\intermediates\symbols\dev\debug --no-version-vectors}

**Comment by aqidd** [comment]
This repository will not be maintained further and we're moving to https://github.com/medigoid/ModularStarter for future development
